name: Film reco avec Docker et PostgreSQL


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set up PostgreSQL container
        uses: docker://postgres:latest
        with:
          args: |
            -e POSTGRES_USER=postgres
            -e POSTGRES_PASSWORD=root
            -e POSTGRES_DB=movies_db
            -p 5432:5432
            -v ./data:/docker-entrypoint-initdb.d

      - name: Run migrations and populate DB
        run: |
          echo "Running SQL migration and inserting data"
          psql -h localhost -U postgres -d movies_db -f ./data/init.sql

      - name: Run tests with pytest
        run: |
          pytest src/api/test_api.py
        # pytest will look for the tests in the src/api/test_api.py file

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          docker push your-image-name

      - name: Upload results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/
